# Generated by Django 5.2.1 on 2025-05-30 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='product',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='price',
            new_name='product_price',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='quantity',
            new_name='product_quantity',
        ),
    ]
